---
require: rubocop-rspec

AllCops:
  DisplayCopNames: true

# Line length 80... what is this, the 90's?
Metrics/LineLength:
  Max: 140

# Rspec
# Ignore block length for spec tests.
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
